#:schema https://mise.jdx.dev/schema/mise.json

[tools]  # tombi: format.rules.table-keys-order = "ascending"
actionlint = "latest"
editorconfig-checker = "latest"
ghalint = "latest"
pinact = "latest"
prek = "latest"
rumdl = "latest"
shellcheck = "latest"
shfmt = "latest"
tombi = "latest"
uv = "latest"
yamllint = "latest"
zizmor = "latest"
