#:schema https://mise.jdx.dev/schema/mise.json

[tools]  # tombi: format.rules.table-keys-order = "ascending"
# tools to use on all my projects
action-validator = "0.9.0"
"aqua:owenlamont/ryl" = "0.24.0"
editorconfig-checker = "4.0.2"
ghalint = "1.5.6"
jactionlint = "2.0.2"
# "pipx:gh-action-pulse" = { version = "latest", uvx = true }
prek = "0.5.5"
rumdl = "0.2.78"
shellcheck = "0.11.0"
shfmt = "3.14.1"
tombi = "1.7.3"
uv = "0.12.24"
yamlfmt = "0.21.0"
zizmor = "1.30.1"
